In [452]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import matplotlib
%matplotlib inline
import seaborn as sns

df = pd.read_csv('Spotify Quarterly.csv')

In [453]:
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')
df['Year'] = df['Date'].dt.year

In [454]:
revenue_df = df.melt(id_vars =['Date','Year'], value_vars =  ['Premium Revenue', 'Ad Revenue'], value_name='revenue', var_name='revenue_type')
revenue_df

Date  Year     revenue_type  revenue
0  2023-03-31  2023  Premium Revenue   2713.0
1  2022-12-31  2022  Premium Revenue   2717.0
2  2022-09-30  2022  Premium Revenue   2651.0
3  2022-06-30  2022  Premium Revenue   2504.0
4  2022-03-31  2022  Premium Revenue   2379.0
5  2021-12-31  2021  Premium Revenue   2295.0
6  2021-09-30  2021  Premium Revenue   2178.0
7  2021-06-30  2021  Premium Revenue   2056.0
8  2021-03-31  2021  Premium Revenue   1931.0
9  2020-12-31  2020  Premium Revenue   1887.0
10 2020-09-30  2020  Premium Revenue   1790.0
11 2020-06-30  2020  Premium Revenue   1758.0
12 2020-03-31  2020  Premium Revenue   1700.0
13 2019-12-31  2019  Premium Revenue   1638.0
14 2019-09-30  2019  Premium Revenue   1561.0
15 2019-06-30  2019  Premium Revenue   1502.0
16 2019-03-31  2019  Premium Revenue   1385.0
17 2018-12-31  2018  Premium Revenue   1320.0
18 2018-09-30  2018  Premium Revenue   1210.0
19 2018-06-30  2018  Premium Revenue   1150.0
20 2018-03-31  2018  Premium Revenue   1037.0
21 2017-12-31  2017  Premium Revenue   1018.0
22 2017-09-30  2017  Premium Revenue    923.0
23 2017-06-30  2017  Premium Revenue    904.0
24 2017-03-31  2017  Premium Revenue    828.0
25 2016-12-31  2016  Premium Revenue      NaN
26 2023-03-31  2023       Ad Revenue    329.0
27 2022-12-31  2022       Ad Revenue    449.0
28 2022-09-30  2022       Ad Revenue    385.0
29 2022-06-30  2022       Ad Revenue    360.0
30 2022-03-31  2022       Ad Revenue    282.0
31 2021-12-31  2021       Ad Revenue    394.0
32 2021-09-30  2021       Ad Revenue    323.0
33 2021-06-30  2021       Ad Revenue    275.0
34 2021-03-31  2021       Ad Revenue    216.0
35 2020-12-31  2020       Ad Revenue    281.0
36 2020-09-30  2020       Ad Revenue    185.0
37 2020-06-30  2020       Ad Revenue    131.0
38 2020-03-31  2020       Ad Revenue    148.0
39 2019-12-31  2019       Ad Revenue    217.0
40 2019-09-30  2019       Ad Revenue    170.0
41 2019-06-30  2019       Ad Revenue    165.0
42 2019-03-31  2019       Ad Revenue    126.0
43 2018-12-31  2018       Ad Revenue    175.0
44 2018-09-30  2018       Ad Revenue    142.0
45 2018-06-30  2018       Ad Revenue    123.0
46 2018-03-31  2018       Ad Revenue    102.0
47 2017-12-31  2017       Ad Revenue    130.0
48 2017-09-30  2017       Ad Revenue    109.0
49 2017-06-30  2017       Ad Revenue    103.0
50 2017-03-31  2017       Ad Revenue     74.0
51 2016-12-31  2016       Ad Revenue      NaN

In [455]:
revenue_cost_df = df.melt(id_vars =['Date','Year'], value_vars =  ['Ad Revenue','Premium Revenue', 'Ad Cost of revenue','Premium Cost Revenue'], value_name='revenue', var_name='revenue_type')
revenue_cost_df.to_csv('revenue_cost.csv', index=False)

In [456]:
df = pd.read_csv('스파르타(튜터) - 스포티파이 데이터.csv')

In [457]:
# 프리미엄 vs 광고
# 프리미엄을 사용하는 고객과 공짜인 고객을 나눠서...프리미엄 고객 , 공짜 컬럼을 만든다. 인덱스 컬럼은 preferred listening content 가 되어야 한다.
# value 값은 비율 -- 34%, 16% 이렇게. 일단 비율을 구해보자.
# preferred listening content 중에서 프리미엄 고객, 공짜 고객을 나눠보자.
# premium_content 중 music, podcast 수를 센다
premium_content = df[['preferred_listening_content', 'spotify_subscription_plan']]
premium_content = premium_content[premium_content['spotify_subscription_plan'] == 'Premium (paid subscription)']
free_content = df[['preferred_listening_content', 'spotify_subscription_plan']]
free_content = free_content[free_content['spotify_subscription_plan'] == 'Free (ad-supported)']

pre_total = premium_content['preferred_listening_content'].count()
pre_music_val = premium_content[premium_content['preferred_listening_content'] == 'Music']['preferred_listening_content'].count()
pre_podcast_val = premium_content[premium_content['preferred_listening_content'] == 'Podcast']['preferred_listening_content'].count()

#ratio
pre_music_ratio = round(pre_music_val / pre_total * 100, 1)
pre_podcast_ratio = round(pre_podcast_val / pre_total * 100, 1)

free_total = free_content['preferred_listening_content'].count()
free_music_val = free_content[free_content['preferred_listening_content'] == 'Music']['preferred_listening_content'].count()
free_podcast_val = free_content[free_content['preferred_listening_content'] == 'Podcast']['preferred_listening_content'].count()

free_music_ratio = round(free_music_val / free_total * 100, 1)
free_podcast_ratio = round(free_podcast_val / free_total * 100, 1)

# 내가 원하는 컬럼은 선호종류, 프리미엄, 애드
# 값은 % 로
dic = {'content':['listening_content', 'listening_content'], 'kind': ['music', 'podcast'], 'premium': [pre_music_ratio, pre_podcast_ratio], 'free': [free_music_ratio, free_podcast_ratio]}
result = pd.DataFrame(dic)

#contingency
dic = {'premium': [pre_music_val, pre_podcast_val], 'free': [free_music_val, free_podcast_val]}
contingency = pd.DataFrame(dic, index=['music', 'podcast'])

In [458]:
contingency

premium  free
music         59   351
podcast       37    73

무료 고객은 음악을 더 선호하고, 유료 고객은 팟캐스트를 더 선호하는 것처럼 보인다.

### listening content 독립성 검사

In [459]:
#chi-square for listening content
# 카이제곱 독립성 검증
# https://ecologyandevolution.org/statsdocs/online-stats-manual-chapter4.html#:~:text=Calculating%20Expected%20Values%20for%20Cells%20in%20Contingency%20Tables&text=The%20expected%20value%20for%20each,dividing%20by%20the%20grand%20total. 
# https://www.analyticsvidhya.com/blog/2023/03/discovering-insights-with-chi-square-tests-a-hands-on-approach-in-python/
# 범주형 (qualitative) 자료의 집단간 동질성 여부를 통계적으로 검증하거나 두변수간의 상관성을 통계적으로 검증 (비모수적)
# 모수 검증은 정규성을 가정, 비모수 검증은 모집단의 분포를 가정하지 않음.
# use cross table for contingency table and chi2_contingency for actual test

from scipy.stats import chi2_contingency
chi, p, dof, expected = chi2_contingency(contingency)
print(f"Chi2: {chi}")
print(f"P-value: {p}")
print(f"Degrees of Freedom: {dof}")
print("Expected Frequencies:")
print(expected)

names = ['listening_content']
chi_lst = [chi]
p_value_lst = [p]
dof_lst = [dof]

Chi2: 20.08232055948347
P-value: 7.417923073190301e-06
Degrees of Freedom: 1
Expected Frequencies:
[[ 75.69230769 334.30769231]
 [ 20.30769231  89.69230769]]


귀무가설: 스포티파이 구독 여부와 listening content 선호는 독립적이다

카이제곱 독립성 검사 결과 p-value 7.4e-6 으로 유의수준 0.05 이하이기에 귀무가설을 기각

기대빈도와 실제 관찰된 빈도를 비교했을때, 구독한 고객이 팟캐스트를 더 선호한다고 결론지을 수 있다.

In [460]:
#usage_period, sub_willingness, preferred_plan, recc_rating, music_genre, time_slot 추가
# result df에 추가하고 csv 파일로 엑스포트
# 태블로에서 각각 7개 토네이도 차트 

premium_content = df[df['spotify_subscription_plan'] == 'Premium (paid subscription)']

# pre_total = premium_content['spotify_usage_period'].count()
pre_one = premium_content[premium_content['spotify_usage_period'] == 'Less than 6 months']['spotify_usage_period'].count()
pre_two = premium_content[premium_content['spotify_usage_period'] == '6 months to 1 year']['spotify_usage_period'].count()
pre_three = premium_content[premium_content['spotify_usage_period'] == '1 year to 2 years']['spotify_usage_period'].count()
pre_four = premium_content[premium_content['spotify_usage_period'] == 'More than 2 years']['spotify_usage_period'].count()

pre_val_lst = [pre_one, pre_two, pre_three, pre_four]
prelst = [0] * len(pre_val_lst)
for i, elem in enumerate(pre_val_lst):
    prelst[i] = round(elem / pre_total * 100, 1)

free_content = df[df['spotify_subscription_plan'] == 'Free (ad-supported)']
# free_total = free_content['spotify_usage_period'].count()
free_one = free_content[free_content['spotify_usage_period'] == 'Less than 6 months']['spotify_usage_period'].count()
free_two = free_content[free_content['spotify_usage_period'] == '6 months to 1 year']['spotify_usage_period'].count()
free_three = free_content[free_content['spotify_usage_period'] == '1 year to 2 years']['spotify_usage_period'].count()
free_four = free_content[free_content['spotify_usage_period'] == 'More than 2 years']['spotify_usage_period'].count()

free_val_lst = [free_one, free_two, free_three, free_four]
freelst = [0] * len(free_val_lst)
for i, elem in enumerate(freelst):
    freelst[i] = round(elem / free_total * 100, 1)
    
dic = {'content': ['usage_period', 'usage_period', 'usage_period', 'usage_period'], 'kind': ['Less than 6 months', '6 months to 1 year', '1 year to 2 years', 'More than 2 years'], 'premium': prelst, 'free': freelst}
result = pd.concat([result , pd.DataFrame(dic)], axis=0)

dic = {'premium': pre_val_lst, 'free': free_val_lst}
contingency = pd.DataFrame(dic, index=['Less than 6 months', '6 months to 1 year', '1 year to 2 years', 'More than 2 years'])

### usage period 독립성 검사
귀무가설: 스포티파이 구독 여부와 usage period 선호는 독립적이다

In [461]:
contingency

premium  free
Less than 6 months        7    84
6 months to 1 year       27    92
1 year to 2 years        31   110
More than 2 years        31   138

In [462]:
#chi-square for usage period
from scipy.stats import chi2_contingency
chi, p, dof, expected = chi2_contingency(contingency)
print(f"Chi2: {chi}")
print(f"P-value: {p}")
print(f"Degrees of Freedom: {dof}")
print("Expected Frequencies:")
print(expected)

names.append('usage_period')
chi_lst.append(chi)
p_value_lst.append(p)
dof_lst.append(dof)

Chi2: 9.588812910417747
P-value: 0.022405070556768027
Degrees of Freedom: 3
Expected Frequencies:
[[ 16.8         74.2       ]
 [ 21.96923077  97.03076923]
 [ 26.03076923 114.96923077]
 [ 31.2        137.8       ]]


p-value 0.02 로 귀무가설을 기각 

In [463]:
# premium_sub_willingness
premium_content = df[df['spotify_subscription_plan'] == 'Premium (paid subscription)']
pre_yes = premium_content[premium_content['premium_sub_willingness'] == 'Yes']['premium_sub_willingness'].count()
pre_no = premium_content[premium_content['premium_sub_willingness'] == 'No']['premium_sub_willingness'].count()

pre_val_lst = [pre_yes, pre_no]
prelst = []
for i, elem in enumerate(pre_val_lst):
    prelst.append(round(elem / pre_total * 100, 1))

free_content = df[df['spotify_subscription_plan'] == 'Free (ad-supported)']
free_yes = free_content[free_content['premium_sub_willingness'] == 'Yes']['premium_sub_willingness'].count()
free_no = free_content[free_content['premium_sub_willingness'] == 'No']['premium_sub_willingness'].count()

free_val_lst = [free_yes, free_no]
freelst = []
for i, elem in enumerate(free_val_lst):
    freelst.append(round(elem / free_total * 100, 1))
    
dic = {'premium': pre_val_lst, 'free': free_val_lst}
contingency = pd.DataFrame(dic, index=['Yes', 'No'])
    
dic = {'content': ['sub_willingness', 'sub_willingness'], 'kind': ['Yes', 'No'], 'premium': prelst, 'free': freelst}
result = pd.concat([result , pd.DataFrame(dic)], axis=0)

In [464]:
contingency

premium  free
Yes       72   114
No        24   310

In [465]:
#chi-square for sub_willingness
from scipy.stats import chi2_contingency
chi, p, dof, expected = chi2_contingency(contingency)
print(f"Chi2: {chi}")
print(f"P-value: {p}")
print(f"Degrees of Freedom: {dof}")
print("Expected Frequencies:")
print(expected)

names.append('sub_willingness')
chi_lst.append(chi)
p_value_lst.append(p)
dof_lst.append(dof)

Chi2: 76.78933394116618
P-value: 1.90202068530302e-18
Degrees of Freedom: 1
Expected Frequencies:
[[ 34.33846154 151.66153846]
 [ 61.66153846 272.33846154]]


p-value 1.9e-18

결론적으로, 구독하지 않은 고객은 미래에도 구독하지 않을 가능성이 크고, 구독한 고객은 계속해서 구독할 것이다.

In [466]:
#preffered_premium_plan
def shorten(elem):
    if elem == 'Individual Plan- Rs 119/ month':
        return 'Individual Plan'
    elif elem == 'Family Plan-Rs 179/month':
        return 'Family Plan'
    elif elem == 'Student Plan-Rs 59/month':
        return 'Student Plan'
    elif elem == 'Duo plan- Rs 149/month':
        return 'Duo Plan'
    else:
        return 'None'

df['preffered_premium_plan'] = df['preffered_premium_plan'].apply(shorten)

premium_content = df[df['spotify_subscription_plan'] == 'Premium (paid subscription)']
pre_one = premium_content[premium_content['preffered_premium_plan'] == 'Individual Plan']['preffered_premium_plan'].count()
pre_two = premium_content[premium_content['preffered_premium_plan'] == 'Family Plan']['preffered_premium_plan'].count()
pre_three = premium_content[premium_content['preffered_premium_plan'] == 'Student Plan']['preffered_premium_plan'].count()
pre_four = premium_content[premium_content['preffered_premium_plan'] == 'Duo Plan']['preffered_premium_plan'].count()
pre_five = premium_content[premium_content['preffered_premium_plan'] == 'None']['preffered_premium_plan'].count()

pre_val_lst = [pre_one, pre_two, pre_three, pre_four, pre_five]
prelst = []
for i, elem in enumerate(pre_val_lst):
    prelst.append(round(elem / pre_total * 100, 1))

free_content = df[df['spotify_subscription_plan'] == 'Free (ad-supported)']
free_one = free_content[free_content['preffered_premium_plan'] == 'Individual Plan']['preffered_premium_plan'].count()
free_two = free_content[free_content['preffered_premium_plan'] == 'Family Plan']['preffered_premium_plan'].count()
free_three = free_content[free_content['preffered_premium_plan'] == 'Student Plan']['preffered_premium_plan'].count()
free_four = free_content[free_content['preffered_premium_plan'] == 'Duo Plan']['preffered_premium_plan'].count()
free_five = free_content[free_content['preffered_premium_plan'] == 'None']['preffered_premium_plan'].count()

free_val_lst = [free_one, free_two, free_three, free_four, free_five]
freelst = []
for i, elem in enumerate(free_val_lst):
    freelst.append(round(elem / free_total * 100, 1))
    
dic = {'premium': pre_val_lst, 'free': free_val_lst}
contingency = pd.DataFrame(dic, index=[['Individual Plan', 'Family Plan', 'Student Plan', 'Duo Plan', 'None']])
    
dic = {'content':['preferred_plan', 'preferred_plan', 'preferred_plan', 'preferred_plan', 'preferred_plan'], 'kind': ['Individual Plan', 'Family Plan', 'Student Plan', 'Duo Plan', 'None'], 'premium': prelst, 'free': freelst}
result = pd.concat([result , pd.DataFrame(dic)], axis=0)

In [467]:
contingency

premium  free
Individual Plan       36    59
Family Plan           17    22
Student Plan           9    85
Duo Plan              26    58
None                   8   200

In [468]:
#chi-square for sub_willingness
from scipy.stats import chi2_contingency
chi, p, dof, expected = chi2_contingency(contingency)
print(f"Chi2: {chi}")
print(f"P-value: {p}")
print(f"Degrees of Freedom: {dof}")
print("Expected Frequencies:")
print(expected)

names.append('preferred_plan')
chi_lst.append(chi)
p_value_lst.append(p)
dof_lst.append(dof)

Chi2: 83.34608496183587
P-value: 3.40236744686884e-17
Degrees of Freedom: 4
Expected Frequencies:
[[ 17.53846154  77.46153846]
 [  7.2         31.8       ]
 [ 17.35384615  76.64615385]
 [ 15.50769231  68.49230769]
 [ 38.4        169.6       ]]


In [469]:
#music_recc_rating

premium_content = df[df['spotify_subscription_plan'] == 'Premium (paid subscription)']
pre_one = premium_content[premium_content['music_recc_rating'] == 1]['music_recc_rating'].count()
pre_two = premium_content[premium_content['music_recc_rating'] == 2]['music_recc_rating'].count()
pre_three = premium_content[premium_content['music_recc_rating'] == 3]['music_recc_rating'].count()
pre_four = premium_content[premium_content['music_recc_rating'] == 4]['music_recc_rating'].count()
pre_five = premium_content[premium_content['music_recc_rating'] == 5]['music_recc_rating'].count()

prelst = [pre_one, pre_two, pre_three, pre_four, pre_five]
for i, elem in enumerate(prelst):
    prelst[i] = round(elem / pre_total * 100, 1)

free_content = df[df['spotify_subscription_plan'] == 'Free (ad-supported)']
free_one = free_content[free_content['music_recc_rating'] == 1]['music_recc_rating'].count()
free_two = free_content[free_content['music_recc_rating'] == 2]['music_recc_rating'].count()
free_three = free_content[free_content['music_recc_rating'] == 3]['music_recc_rating'].count()
free_four = free_content[free_content['music_recc_rating'] == 4]['music_recc_rating'].count()
free_five = free_content[free_content['music_recc_rating'] == 5]['music_recc_rating'].count()

freelst = [free_one, free_two, free_three, free_four, free_five]
for i, elem in enumerate(freelst):
    freelst[i] = round(elem / free_total * 100, 1)
    
dic = {'content': ['recc_rating', 'recc_rating', 'recc_rating', 'recc_rating', 'recc_rating'], 'kind': ['5', '4', '3', '2', '1'], 'premium': prelst, 'free': freelst}
result = pd.concat([result , pd.DataFrame(dic)], axis=0)

In [470]:
df['fav_music_genre'].unique()

array(['classical', 'Rock', 'Rap', 'Electronic/Dance', 'Pop', 'Melody',
       'All', 'Classical & melody, dance', 'Old songs', 'Kpop',
       'trending songs random'], dtype=object)

In [471]:
#fav_music_genre

genre_lst = ['classical', 'Rock', 'Rap', 'Electronic/Dance', 'Pop', 'Melody', 'All', 'Classical & melody, dance', 'Old songs', 'Kpop', 'trending songs random']

premium_content = df[df['spotify_subscription_plan'] == 'Premium (paid subscription)']
pre_val_lst = []
for elem in genre_lst:
    x = premium_content[premium_content['fav_music_genre'] == elem]['fav_music_genre'].count()
    pre_val_lst.append(x)
prelst = []
for i, elem in enumerate(pre_val_lst):
    prelst.append(round(elem / pre_total * 100, 1))

free_content = df[df['spotify_subscription_plan'] == 'Free (ad-supported)']
free_val_lst = []
for elem in genre_lst:
    x = free_content[free_content['fav_music_genre'] == elem]['fav_music_genre'].count()
    free_val_lst.append(x)
freelst = []
for i, elem in enumerate(free_val_lst):
    freelst.append(round(elem / free_total * 100, 1))
    
dic = {'premium': pre_val_lst, 'free': free_val_lst}
contingency = pd.DataFrame(dic, index=genre_lst)

content = ['music_genre'] * len(genre_lst)
dic = {'content': content, 'kind': genre_lst, 'premium': prelst, 'free': freelst}
result = pd.concat([result , pd.DataFrame(dic)], axis=0)

In [472]:
contingency

premium  free
classical                       25    62
Rock                             2     2
Rap                             19    36
Electronic/Dance                 4    12
Pop                             17    68
Melody                          28   231
All                              1     5
Classical & melody, dance        0     2
Old songs                        0     1
Kpop                             0     4
trending songs random            0     1

In [473]:
#chi-square for music genre
from scipy.stats import chi2_contingency
chi, p, dof, expected = chi2_contingency(contingency)
print(f"Chi2: {chi}")
print(f"P-value: {p}")
print(f"Degrees of Freedom: {dof}")
print("Expected Frequencies:")
print(expected)

names.append('music_genre')
chi_lst.append(chi)
p_value_lst.append(p)
dof_lst.append(dof)

Chi2: 30.67882230577416
P-value: 0.0006628217729379874
Degrees of Freedom: 10
Expected Frequencies:
[[1.60615385e+01 7.09384615e+01]
 [7.38461538e-01 3.26153846e+00]
 [1.01538462e+01 4.48461538e+01]
 [2.95384615e+00 1.30461538e+01]
 [1.56923077e+01 6.93076923e+01]
 [4.78153846e+01 2.11184615e+02]
 [1.10769231e+00 4.89230769e+00]
 [3.69230769e-01 1.63076923e+00]
 [1.84615385e-01 8.15384615e-01]
 [7.38461538e-01 3.26153846e+00]
 [1.84615385e-01 8.15384615e-01]]


In [474]:
#music_time_slot
timeslot_lst = ['Night', 'Morning', 'Afternoon']

premium_content = df[df['spotify_subscription_plan'] == 'Premium (paid subscription)']
pre_val_lst = []
for elem in timeslot_lst:
    x = premium_content[premium_content['music_time_slot'] == elem]['music_time_slot'].count()
    pre_val_lst.append(x)
prelst = []
for i, elem in enumerate(pre_val_lst):
    prelst.append(round(elem / pre_total * 100, 1))

free_content = df[df['spotify_subscription_plan'] == 'Free (ad-supported)']
free_val_lst = []
for elem in timeslot_lst:
    x = free_content[free_content['music_time_slot'] == elem]['music_time_slot'].count()
    free_val_lst.append(x)
freelst = []
for i, elem in enumerate(free_val_lst):
    freelst.append(round(elem / free_total * 100, 1))
    
dic = {'premium' : pre_val_lst, 'free' : free_val_lst}
contingency = pd.DataFrame(dic, index=timeslot_lst)

content = ['time_slot'] * 3
dic = {'content': content, 'kind': timeslot_lst, 'premium': prelst, 'free': freelst}
result = pd.concat([result , pd.DataFrame(dic)], axis=0)

In [475]:
contingency

premium  free
Night           44   268
Morning         16    75
Afternoon       36    81

In [476]:
#chi-square for timeslot
from scipy.stats import chi2_contingency
chi, p, dof, expected = chi2_contingency(contingency)
print(f"Chi2: {chi}")
print(f"P-value: {p}")
print(f"Degrees of Freedom: {dof}")
print("Expected Frequencies:")
print(expected)

names.append('time_slot')
chi_lst.append(chi)
p_value_lst.append(p)
dof_lst.append(dof)

Chi2: 15.758460616951181
P-value: 0.00037852429162680065
Degrees of Freedom: 2
Expected Frequencies:
[[ 57.6 254.4]
 [ 16.8  74.2]
 [ 21.6  95.4]]


In [477]:
dic = {'names':names, 'chi2':chi_lst, 'p-value':p_value_lst, 'dof':dof_lst}
chi_df = pd.DataFrame(dic)

In [478]:
chi_df

names       chi2       p-value  dof
0  listening_content  20.082321  7.417923e-06    1
1       usage_period   9.588813  2.240507e-02    3
2    sub_willingness  76.789334  1.902021e-18    1
3     preferred_plan  83.346085  3.402367e-17    4
4        music_genre  30.678822  6.628218e-04   10
5          time_slot  15.758461  3.785243e-04    2

In [479]:
result

content                       kind  premium  free
0   listening_content                      music     61.5  82.8
1   listening_content                    podcast     38.5  17.2
0        usage_period         Less than 6 months      7.3   0.0
1        usage_period         6 months to 1 year     28.1   0.0
2        usage_period          1 year to 2 years     32.3   0.0
3        usage_period          More than 2 years     32.3   0.0
0     sub_willingness                        Yes     75.0  26.9
1     sub_willingness                         No     25.0  73.1
0      preferred_plan            Individual Plan     37.5  13.9
1      preferred_plan                Family Plan     17.7   5.2
2      preferred_plan               Student Plan      9.4  20.0
3      preferred_plan                   Duo Plan     27.1  13.7
4      preferred_plan                       None      8.3  47.2
0         recc_rating                          5      3.1   2.6
1         recc_rating                          4     27.1   7.1
2         recc_rating                          3     35.4  36.8
3         recc_rating                          2     20.8  36.3
4         recc_rating                          1     13.5  17.2
0         music_genre                  classical     26.0  14.6
1         music_genre                       Rock      2.1   0.5
2         music_genre                        Rap     19.8   8.5
3         music_genre           Electronic/Dance      4.2   2.8
4         music_genre                        Pop     17.7  16.0
5         music_genre                     Melody     29.2  54.5
6         music_genre                        All      1.0   1.2
7         music_genre  Classical & melody, dance      0.0   0.5
8         music_genre                  Old songs      0.0   0.2
9         music_genre                       Kpop      0.0   0.9
10        music_genre      trending songs random      0.0   0.2
0           time_slot                      Night     45.8  63.2
1           time_slot                    Morning     16.7  17.7
2           time_slot                  Afternoon     37.5  19.1

In [480]:
# result.to_csv('ratio_2.csv', index=False)

In [481]:
# podcast 선호 비율
dic = {'user': ['Free', 'Premium'], 'conversion_rate_before':[17.22, 38.54], 'conversion_rate_after':[16.67, 38.54]}
temp = pd.DataFrame(dic)
temp.to_csv('permutation_2.csv', index=False)